name: llm_runner
description: A Rust-powered library to run AI models locally in Flutter apps.
version: 0.0.1
repository: https://github.com/deadcow-labs/rust-llm-flutter
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1

ffigen:
  name: 'LlmBindings'
  description: 'Bindings for Rust code'
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - '/Users/lautarosuarez/Documents/opensource/llm_runner/rust/include/llm_runner.h'
    include-directives:
      - '/Users/lautarosuarez/Documents/opensource/llm_runner/rust/include/*.h'
  llvm-path:
    - '/usr/local/opt/llvm'
    - '/usr/lib/llvm-14'
