name: llm_runner
description: A Rust-powered library to run AI models locally in Flutter apps.
version: 0.1.0
repository: https://github.com/deadcow-labs/rust-llm-flutter
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.1  # For FFI bridge to Rust
  http: ^0.13.5  # Used for downloading models

dev_dependencies:
  ffigen: ^12.0.0  # Generates Rust-Dart FFI bindings

ffigen:
  name: 'LlmBindings'
  description: 'Bindings for Rust code'
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - '/Users/lautarosuarez/Documents/opensource/llm_runner/rust/include/llm_runner.h'
    include-directives:
      - '/Users/lautarosuarez/Documents/opensource/llm_runner/rust/include/*.h'
  llvm-path:
    - '/usr/local/opt/llvm'
    - '/usr/lib/llvm-14'
