/* Generated by cbindgen */

#ifndef BRIDGE_GENERATED_H
#define BRIDGE_GENERATED_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *load_model_ffi(const char *model_name);

char *run_inference_ffi(const char *input_text);

char *download_model_ffi(const char *model_name);

void *tokenize_text(const char *_text);

char *detokenize_ids(const uint32_t *_tokens, uintptr_t _length);

#endif /* BRIDGE_GENERATED_H */
