name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Build
        run: |
          ./build_mobile.sh
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            flutter_package/ios/Frameworks/libllm_runner.a